export const MESSAGE = {
  COMMON: {
    BAD_REQUEST: "Parameter tidak valid",
    SUCCESS_UPDATE: "Data berhasil diperbarui",
    UNAUTHORIZED: "Tidak diizinkan",
    FORBIDDEN: "Akses ditolak",
    INTERNAL_SERVER_ERROR: "Terjadi kesalahan pada server",
  },
  USER: {
    FOUND: "Data user berhasil ditemukan",
    NOT_FOUND: "Data user tidak ditemukan",
    CREATED: "Data User berhasil ditambahkan",
    DELETED: "Data User berhasil dihapus",
    EMAIL_ALREADY_USED: "Email atau username sudah digunakan",
  },
  AUTH: {
    REGISTER_SUCCESS: "Register berhasil",
    LOGIN_SUCCESS: "Login berhasil",
    LOGOUT_SUCCESS: "Logout berhasil",
    PROFILE_SUCCESS: "Data profil berhasil diambil",
    ROLE_SELECTED: "Role berhasil dipilih",
    INVALID_CREDENTIALS: "Email atau password salah",
    NO_TOKEN: "Token tidak ditemukan, akses ditolak",
    TOKEN_INVALID: "Token tidak valid atau sudah kadaluarsa",
    ROLE_NOT_FOUND: "User tidak memiliki role tersebut",
  },
  STORE: {
    CREATED: "Toko berhasil dibuat",
    FETCHED: "Data toko berhasil diambil",
    UPDATED: "Toko berhasil diupdate",
    DELETED: "Toko berhasil dihapus",
    NOT_FOUND: "Toko tidak ditemukan",
    ALREADY_EXISTS: "Seller sudah memiliki toko",
    UNAUTHORIZED: "Anda tidak berhak mengakses toko ini",
    REVENUE_FETCHED: "Laporan pendapatan berhasil diambil",
  },
  PRODUCT: {
    CREATED: "Produk berhasil dibuat",
    FETCHED: "Data produk berhasil diambil",
    UPDATED: "Produk berhasil diupdate",
    DELETED: "Produk berhasil dihapus",
    NOT_FOUND: "Produk tidak ditemukan",
    NO_STORE: "Seller belum memiliki toko",
  },
  WALLET: {
    FETCHED: "Data dompet berhasil diambil",
    HISTORY_FETCHED: "Riwayat transaksi berhasil diambil",
    TOPUP_SUCCESS: "Top up berhasil",
    INSUFFICIENT_BALANCE: "Saldo tidak mencukupi",
  },
  CART: {
    ADDED: "Produk berhasil ditambah ke keranjang",
    FETCHED: "Keranjang berhasil diambil",
    UPDATED: "Keranjang berhasil diupdate",
    DELETED: "Item keranjang berhasil dihapus",
    NOT_FOUND: "Item keranjang tidak ditemukan",
    EMPTY: "Keranjang kosong",
  },
  ORDER: {
    CHECKOUT_SUCCESS: "Checkout berhasil",
    FETCHED: "Data pesanan berhasil diambil",
    STATUS_UPDATED: "Status pesanan berhasil diupdate",
    NOT_FOUND: "Pesanan tidak ditemukan",
  },
  DRIVER: {
    JOBS_FETCHED: "Daftar pekerjaan tersedia",
    JOB_TAKEN: "Pekerjaan berhasil diambil",
    JOB_COMPLETED: "Pekerjaan berhasil diselesaikan",
    JOB_UNAVAILABLE: "Pekerjaan tidak tersedia atau sudah diambil",
  },
  ADMIN: {
    VOUCHER_CREATED: "Voucher berhasil dibuat",
    VOUCHERS_FETCHED: "Data voucher",
    DASHBOARD_FETCHED: "Data dashboard admin",
  },
  ADDRESS: {
    CREATED: "Alamat berhasil ditambahkan",
    FETCHED: "Data alamat berhasil diambil",
    UPDATED: "Alamat berhasil diupdate",
    DELETED: "Alamat berhasil dihapus",
    NOT_FOUND: "Alamat tidak ditemukan",
  },
  REVIEW: {
    CREATED: "Ulasan berhasil dikirim",
    FETCHED: "Ulasan berhasil diambil",
    NOT_BOUGHT: "Anda hanya bisa memberi ulasan pada produk yang sudah dibeli",
  },
  VOUCHER: {
    FETCHED: "Voucher berhasil diambil",
  }
};
